binop_separator = "Front"
condense_wildcard_suffixes = true
error_on_line_overflow = false
fn_single_line = true
match_block_trailing_comma = true
max_width = 80
normalize_comments = true
reorder_imports = true
use_try_shorthand = true
struct_field_align_threshold = 20
blank_lines_upper_bound = 3

unstable_features = true
format_strings = true
imports_layout = "Vertical"
imports_indent = "Block"
merge_imports = true
force_multiline_blocks = true
# indent_style = "Visual"
